--------------------------------------------------------
--  Fichier créé - dimanche-décembre-15-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."USERS" 
   (	"ID_USER" NUMBER, 
	"USERNAME" VARCHAR2(20 BYTE), 
	"EMAILUSER" VARCHAR2(20 BYTE), 
	"PASSWORDUSER" VARCHAR2(20 BYTE), 
	"FIRSTNAME" VARCHAR2(20 BYTE), 
	"LASTNAME" VARCHAR2(20 BYTE), 
	"PHONENUMBERUSER" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.USERS
SET DEFINE OFF;
Insert into SYSTEM.USERS (ID_USER,USERNAME,EMAILUSER,PASSWORDUSER,FIRSTNAME,LASTNAME,PHONENUMBERUSER) values ('1','ClemLeBG','CT','CT','Clement','Temil','0670220473');
Insert into SYSTEM.USERS (ID_USER,USERNAME,EMAILUSER,PASSWORDUSER,FIRSTNAME,LASTNAME,PHONENUMBERUSER) values ('2','JujuLPB','JF','JF','Justine','Foulquier','0645658983');
Insert into SYSTEM.USERS (ID_USER,USERNAME,EMAILUSER,PASSWORDUSER,FIRSTNAME,LASTNAME,PHONENUMBERUSER) values ('3','MattBoMal','MH','MH','Matthew','Haas','0769193310');
Insert into SYSTEM.USERS (ID_USER,USERNAME,EMAILUSER,PASSWORDUSER,FIRSTNAME,LASTNAME,PHONENUMBERUSER) values ('4','AlexSexy','AA','AA','Alexis','Andre','0672791302');



  CREATE TABLE "SYSTEM"."BDE" 
   (	"ID_BDE" NUMBER, 
	"IDCREATOR" VARCHAR2(20 BYTE), 
	"NAMEBDE" VARCHAR2(50 BYTE), 
	"SCHOOLBDE" VARCHAR2(200 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.BDE
SET DEFINE OFF;
Insert into SYSTEM.BDE (ID_BDE,IDCREATOR,NAMEBDE,SCHOOLBDE) values ('2','1','BDE','Polytech Montpellier');
Insert into SYSTEM.BDE (ID_BDE,IDCREATOR,NAMEBDE,SCHOOLBDE) values ('2','1','BDE','Polytech Grenoble');
--------------------------------------------------------
--  Constraints for Table BDE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."BDE" MODIFY ("IDCREATOR" NOT NULL ENABLE);
